[package]
authors = ['GalacticCouncil']
description = 'Tetched Claims Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-node'
license = 'Apache 2.0'
name = 'noble-claims'
repository = 'https://github.com/galacticcouncil/hydradx-node'
version = '3.0.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
# Substrate dependencies
frame-benchmarking = {version = "3.0.0", default-features = false, optional = true}
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
hex = {default-features = false, version = "0.4.2"}
hex-literal = '0.3.1'
lazy_static = {features = ['spin_no_std'], version = "1.4.0"}
rustc-hex = {version = '2.1.0', default-features = false}
serde = {optional = true, version = '1.0.101', features = ['derive']}
sp-io = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}

# Local dependencies
primitives = {path = '../../primitives', default-features = false}

# ORML dependencies
orml-tokens = {default-features = false, version = '0.4.1-dev'}
orml-traits = {default-features = false, version = '0.4.1-dev'}
orml-utilities = {default-features = false, version = '0.4.1-dev'}

[dev-dependencies]
hex-literal = '0.3.1'
pallet-balances = {version = "3.0.0"}
sp-core = {default-features = false, version = '3.0.0'}

[features]
default = ['std']
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'orml-traits/std',
  'orml-tokens/std',
  'orml-utilities/std',
  'primitives/std',
  'rustc-hex/std',
  'serde/std',
]
