[package]
authors = ['GalacticCouncil']
build = 'build.rs'
description = 'Hydra DX'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-node'
license = 'Apache 2.0'
name = 'hydra-dx'
repository = 'https://github.com/galacticcouncil/hydradx-node'
version = '5.0.0'

[[bin]]
name = 'tetched-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
hydra-dx-build-script-utils = {path = '../utils/build-script-utils'}

[dependencies]
jsonrpc-core = '15.0.0'
serde_json = "1.0.61"
structopt = '0.3.8'

# local dependencies
hydra-dx-runtime = {path = '../runtime'}
pallet-xyk-rpc = {path = '../pallets/xyk/rpc'}
primitives = {path = '../primitives'}

# Substrate dependencies
frame-benchmarking = '3.0.0'
frame-benchmarking-cli = {version = '3.0.0', optional = true}
futures = '0.3.4'
hex-literal = "0.3.1"
pallet-im-online = "3.0.0"
pallet-staking = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-authority-discovery = '0.9.0'
sc-basic-authorship = '0.9.0'
sc-cli = {features = ['wasmtime'], version = '0.9.0'}
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-babe = '0.9.0'
sc-consensus-babe-rpc = '0.9.0'
sc-consensus-epochs = '0.9.0'
sc-consensus-slots = '0.9.0'
sc-executor = {features = ['wasmtime'], version = '0.9.0'}
sc-finality-grandpa = '=0.9.0'
sc-finality-grandpa-rpc = '=0.9.0'
sc-keystore = '3.0.0'
sc-network = '0.9.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = '0.9.0'
sc-telemetry = '3.0.0'
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-authority-discovery = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-babe = '0.9.0'
sp-core = '=3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-keystore = '0.9.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'

[features]
default = [
  "frame-benchmarking-cli",
]
runtime-benchmarks = [
  'hydra-dx-runtime/runtime-benchmarks',
  "frame-benchmarking-cli",
]
